import {getdataonevent as getdata} from "../../protected-scripts/util.js";
const urlParams = new URLSearchParams(window.location.search);
const userid = urlParams.get('userid');
const data = await getdata(`user_profile?userid=${userid}`);
const img = data.personimage;
if (img === 'Empty') document.querySelector('.profile-pic').src = '/images/blank_profile_pic.png';
else document.querySelector('.profile-pic').src = data.personimage;
document.querySelector('.user-name').textContent = data.personname;
document.querySelector('.batch').textContent = `Batch: ${data.details.batch}`;
document.querySelector('.branch').textContent = `Branch: ${data.details.branch}`;
document.querySelector('.about-me').innerText = data.details.aboutme;
document.querySelector('.education').innerText = data.details.education;
document.querySelector('.role').innerText = data.details.currentrole;
document.querySelector('.experience').innerText = data.details.experience;
document.querySelector('.contact-info ').innerText = data.details.contactinfo;